#:schema node_modules/wrangler/config-schema.json
name = "bright-mind"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


[placement]
mode = "smart"

[vars]
NODE_VERSION="20.0.0" # don't remove
GOOGLE_GENERATIVE_AI_API_KEY = "xxxxxxx"
OPENAI_API_KEY="sk-proj-xxxxxxx"
UPSTASH_VECTOR_REST_URL="https://xxxxxxx.upstash.io"
UPSTASH_VECTOR_REST_TOKEN="ABxxxxxxxxxxxxxxxx"

[[kv_namespaces]]
binding = "XXXXXX_PROJECT_NAME"
id = "e22a7xxxxxxxxxxxxxxxxxxxxxff6"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#kv-namespaces
# KV Example:
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"



# To use different bindings for preview and production environments, follow the examples below.
# When using environment-specific overrides for bindings, ALL bindings must be specified on a per-environment basis.
# Docs: https://developers.cloudflare.com/pages/functions/wrangler-configuration#environment-specific-overrides

######## PREVIEW environment config ########

# [env.preview.vars]
# API_KEY = "xyz789"

# [[env.preview.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PREVIEW_NAMESPACE_ID>"

######## PRODUCTION environment config ########

# [env.production.vars]
# API_KEY = "abc123"

# [[env.production.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PRODUCTION_NAMESPACE_ID>"
